export default [
    {
        "id":"1",
        "genres":"Sports",
        'name':"Football",
        "isTrending":true,
        "tweets":'120k'
    },
    {
        "id":"2",
        "genres":"Entertainment",
        'name':"Movie",
        "isTrending":true,
        "tweets":'100k'
    },
    {
        "id":"3",
        "genres":"Politics",
        'name':"Elections",
        "isTrending":false,
        "tweets":'12k'
    },
    {
        "id":"4",
        "genres":"Music",
        'name':"Rap",
        "isTrending":true,
        "tweets":'133k'
    },
    {
        "id":"5",
        "genres":"Entertainment",
        'name':"KapilSharmaShow",
        "isTrending":false,
        "tweets":'90k'
    },
    {
        "id":"6",
        "genres":"Sports",
        'name':"Basketball",
        "isTrending":true,
        "tweets":'500k'
    },
    {
        "id":"7",
        "genres":"Sports",
        'name':"Chess",
        "isTrending":false,
        "tweets":'50k'
    },
    {
        "id":"8",
        "genres":"Entertainment",
        'name':"#Prabas",
        "isTrending":false,
        "tweets":'90k'
    },
    {
        "id":"9",
        "genres":"Entertainment",
        'name':"#Bahubali",
        "isTrending":false,
        "tweets":'90k'
    },
    {
        "id":"10",
        "genres":"Entertainment",
        'name':"#ABCD",
        "isTrending":false,
        "tweets":'90k'
    },
]